### ISSUE TITLE
Multiple search terms don't work as expected

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#156]
This isn't very good. 

Search for one term e.g. `lleyn`
http://topcat/app/#/?q=lleyn gives 12 results

Add another e.g. `lleyn habitat` gives >800 results
http://topcat/app/#/?q=lleyn%20habitat 

Multiple search terms should 'AND', not 'OR'.

**Comment by ulric-wilson** [comment]
Yes enhanced search would be very beneficial.  ideally AND  / Or / NOT and quoted exact phrases e.g. "lleyn habitat"

**Comment by ulric-wilson** [comment]
Further support for this from Luke and Cathy who are using TC in earnest to clean up publication records imported from website.   

User comment "Allow use of double quotes to connect two or more words so that the search can be narrowed down to the exact request (at the moment searching for multiple words brings up results that contains at least one of those words and results in a bloated amount of results.)"

**Comment by CathyJinJNCC** [comment]
ANDing the terms instead of ORing is quite strict and you can easily get no results back at all which doesn't look good. Adding phrase searches in quotes instead of just term searches seems to work quite well and should hopefully be good enough for narrowing down results.

**Comment by SoniaKhela** [comment]
"lleyn habitat" = 0 records. 'lleyn habitat' = 1778 so it is searching habitat as an individual word
